version: '3.3'

services:
   myimage:
       build:
         context: .
         dockerfile: Dockerfile
       ports:
         - "80:80"
       networks:
         - sonarnet
       tty: true
       command: top
   db:
     image: mysql:5.7
     networks:
       - sonarnet
     restart: always
     volumes:
       - /mnt/sda1/var/mysql_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: sonar
       MYSQL_USER: sonar
       MYSQL_PASSWORD: sonar
volumes:
  db_data: {}

networks:
  sonarnet:
    driver: bridge
