version: '3.3'

services:
   myimage:
       build:
         context: .
         dockerfile: Dockerfile
       ports:
         - "9000:9000"
       networks:
         - sonarnet
       tty: true
       command: top
       volumes:
         - static:/tmp
   db:
     image: mysql:5.7
     networks:
       - sonarnet
     restart: always
     volumes:
       - /mnt/sda1/var/mysql_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: sonar
       MYSQL_USER: sonar
       MYSQL_PASSWORD: sonar
     
volumes:
  static:
    driver: local
    driver_opts:
      type: none
      device: /mnt/sda1/var/sonar-bonar
      o: bind

networks:
  sonarnet:
    driver: bridge
